version: "3.8"

services:
  app:
    container_name: "modinity-pokemon-service"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_PATH=${DB_PATH}
    restart: always
